spring:
  datasource:
    # Database URL
    url: jdbc:mysql://localhost:3306/playground
    # Database credentials
    username: root
    password:
  # Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
management:
  endpoint:
    health:
      show-details: always
